name: Add Issue Extension
on:
  workflow_dispatch:

jobs:
  add_issue_extension:
    # Not a fork
    if: github.repository == 'codinasion/hello-world'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache PIP packages
        id: cache-pip-packages
        uses: actions/cache@v2
        with:
          path: .venv
          key: pip-packages-${{ hashFiles('requirements.txt') }}

      - name: Install PIP packages
        if: steps.cache-pip-packages.outputs.cache-hit != 'true'
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Add Issue Extension
        run: |
          source .venv/bin/activate
          python3 script/add_issue_extension.py "${{ secrets.REPO_TOKEN }}"
